import ROLES from "./roles.js";
import PERMISSIONS from "./permission.js";

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.MANAGE_SUPER_ADMINS,
    PERMISSIONS.MANAGE_ADMINS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_BATCHES,
    PERMISSIONS.MANAGE_TEAMS,
    PERMISSIONS.VIEW_TEAMS,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.MANAGE_MILESTONES,
    PERMISSIONS.VIEW_MILESTONES,
    PERMISSIONS.MANAGE_SPRINTS,
    PERMISSIONS.VIEW_SPRINTS,
    PERMISSIONS.REVIEW_DELIVERABLES,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.EVALUATE_STUDENTS,
    PERMISSIONS.MANAGE_RESOURCES,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.CREATE_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.SYSTEM_CONFIGURATION,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_BATCHES,
    PERMISSIONS.MANAGE_TEAMS,
    PERMISSIONS.VIEW_TEAMS,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.MANAGE_MILESTONES,
    PERMISSIONS.VIEW_MILESTONES,
    PERMISSIONS.MANAGE_SPRINTS,
    PERMISSIONS.VIEW_SPRINTS,
    PERMISSIONS.REVIEW_DELIVERABLES,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.EVALUATE_STUDENTS,
    PERMISSIONS.MANAGE_RESOURCES,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.CREATE_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_TEAMS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_MILESTONES,
    PERMISSIONS.VIEW_SPRINTS,
    PERMISSIONS.SUBMIT_DELIVERABLES,
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
    PERMISSIONS.VIEW_OWN_EVALUATION,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_OWN_REPORTS,
  ],
};

export default ROLE_PERMISSIONS;

