import ROLES from "./roles.js";
import PERMISSIONS from "./permission.js";

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.MANAGE_SUPER_ADMINS,
    PERMISSIONS.MANAGE_ADMINS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_BATCHES,
    // Teams
    PERMISSIONS.MANAGE_TEAMS,
    PERMISSIONS.VIEW_TEAMS,
    // Projects
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.VIEW_PROJECTS,
    // Milestones
    PERMISSIONS.MANAGE_MILESTONES,
    PERMISSIONS.VIEW_MILESTONES,
    // Sprints
    PERMISSIONS.MANAGE_SPRINTS,
    PERMISSIONS.VIEW_SPRINTS,
    // Tasks
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASKS,
    PERMISSIONS.UPDATE_TASKS,
    PERMISSIONS.DELETE_TASKS,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.UPDATE_OWN_TASKS,
    PERMISSIONS.VIEW_OWN_TASKS,
    // Deliverables
    PERMISSIONS.REVIEW_DELIVERABLES,
    // Attendance
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    // Evaluations
    PERMISSIONS.EVALUATE_STUDENTS,
    // Resources
    PERMISSIONS.MANAGE_RESOURCES,
    PERMISSIONS.VIEW_RESOURCES,
    // Announcements
    PERMISSIONS.CREATE_ANNOUNCEMENTS,
    PERMISSIONS.UPDATE_ANNOUNCEMENTS,
    PERMISSIONS.DELETE_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    // Reports
    PERMISSIONS.VIEW_REPORTS,
    // System
    PERMISSIONS.SYSTEM_CONFIGURATION,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_BATCHES,
    // Teams
    PERMISSIONS.MANAGE_TEAMS,
    PERMISSIONS.VIEW_TEAMS,
    // Projects
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.VIEW_PROJECTS,
    // Milestones
    PERMISSIONS.MANAGE_MILESTONES,
    PERMISSIONS.VIEW_MILESTONES,
    // Sprints
    PERMISSIONS.MANAGE_SPRINTS,
    PERMISSIONS.VIEW_SPRINTS,
    // Tasks
    PERMISSIONS.MANAGE_TASKS,
    PERMISSIONS.VIEW_TASKS,
    PERMISSIONS.CREATE_TASKS,
    PERMISSIONS.UPDATE_TASKS,
    PERMISSIONS.DELETE_TASKS,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.UPDATE_OWN_TASKS,
    PERMISSIONS.VIEW_OWN_TASKS,
    // Deliverables
    PERMISSIONS.REVIEW_DELIVERABLES,
    // Attendance
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    // Evaluations
    PERMISSIONS.EVALUATE_STUDENTS,
    // Resources
    PERMISSIONS.MANAGE_RESOURCES,
    PERMISSIONS.VIEW_RESOURCES,
    // Announcements
    PERMISSIONS.CREATE_ANNOUNCEMENTS,
    PERMISSIONS.UPDATE_ANNOUNCEMENTS,
    PERMISSIONS.DELETE_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    // Reports
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_TEAMS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_MILESTONES,
    PERMISSIONS.VIEW_SPRINTS,
    PERMISSIONS.SUBMIT_DELIVERABLES,
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
    PERMISSIONS.VIEW_OWN_EVALUATION,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_OWN_REPORTS,
    PERMISSIONS.VIEW_OWN_TASKS,
    PERMISSIONS.UPDATE_OWN_TASKS,
  ],
};

export default ROLE_PERMISSIONS;
